=== Gurtovoy/antharasl2/gameserver/data/items/item.dtd
<!ELEMENT list (weapon|etcitem|armor)*>
<!ELEMENT weapon  (set|equip|for|cond|skills|triggers|attributes|enchant_options|crystallization_info)*>
<!ATTLIST weapon
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT etcitem (set|equip|for|cond|skills|triggers|enchant_options|capsuled_items|crystallization_info)*>
<!ATTLIST etcitem
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT armor  (set|equip|for|cond|skills|triggers|attributes|enchant_options|crystallization_info|agathion_data)*>
<!ATTLIST armor
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>

<!ELEMENT enchant_options (level)*>
<!ELEMENT level (option)*>
<!ATTLIST level
	value CDATA #REQUIRED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	id CDATA #REQUIRED>

<!ELEMENT equip (slot)*>
<!ELEMENT slot (#PCDATA)>
<!ATTLIST slot
	id CDATA #REQUIRED>

<!ELEMENT cond (player|target|using|zone|or|not|and)*>
<!ATTLIST cond
	msgId CDATA #IMPLIED>
<!ELEMENT or (player|target|using|zone|or|not|and)*>
<!ELEMENT not (player|target|using|zone|or|not|and)*>
<!ELEMENT and (player|target|using|zone|or|not|and)*>
<!ELEMENT player (#PCDATA)>
<!ATTLIST player
	residence CDATA #IMPLIED
	olympiad CDATA #IMPLIED
	race CDATA #IMPLIED
	instance_zone CDATA #IMPLIED
	is_clan_leader CDATA #IMPLIED
	sex CDATA #IMPLIED
	castle_type CDATA #IMPLIED
	classId CDATA #IMPLIED
	minLevel CDATA #IMPLIED
	max_level CDATA #IMPLIED
	avail_max_sp CDATA #IMPLIED
	quest_state CDATA #IMPLIED
	min_pledge_rank CDATA #IMPLIED
	class_type CDATA #IMPLIED
	min_clan_level CDATA #IMPLIED
	isFlagged CDATA #IMPLIED
	is_hero CDATA #IMPLIED
	is_chaotic CDATA #IMPLIED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	is_pet_feed CDATA #IMPLIED
	type CDATA #IMPLIED>
<!ELEMENT using (#PCDATA)>
<!ATTLIST using
	slotitem CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	type CDATA #IMPLIED
	name CDATA #IMPLIED>

<!ELEMENT for (add|set|mul)*>
<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT attributes (attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
	element CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT capsuled_items (capsuled_item)*>
<!ELEMENT capsuled_item (#PCDATA)>
<!ATTLIST capsuled_item
	id CDATA #REQUIRED
	min_count CDATA #REQUIRED
	max_count CDATA #REQUIRED
	chance CDATA #REQUIRED
	enchant_level CDATA #IMPLIED>

<!ELEMENT mul (player|target|using|zone)*>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	name CDATA #IMPLIED
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>

<!ELEMENT skills (skill|enchant_skill)*>

	<!ELEMENT skill (#PCDATA)>
	<!ATTLIST skill
		id CDATA #REQUIRED
		level CDATA #REQUIRED>

	<!ELEMENT enchant_skill (#PCDATA)>
	<!ATTLIST enchant_skill
		id CDATA #REQUIRED
		level CDATA #REQUIRED
		enchant CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED
	cancel_effects_on_remove CDATA #IMPLIED>

<!ELEMENT agathion_data (enchant)*>

<!ELEMENT enchant (main_skills|sub_skills)*>
<!ATTLIST enchant
	level CDATA #REQUIRED>

<!ELEMENT main_skills (skill)*>
<!ELEMENT sub_skills (skill)*>

=== Gurtovoy/antharasl2/gameserver/data/items/26300-26399.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="26326" name="Lineage II Baseball Uniform">
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.london_olympic_bikini"/>
		<set name="type" value="HEAVY"/>
		<set name="weight" value="1000"/>
		<equip>
			<slot id="FORMAL_WEAR"/>
		</equip>
	</armor>
	<armor id="26327" name="Lineage II Baseball Cap">
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.accessory_mining_cap_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
	<etcitem id="26354" name="Gem">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="icon.etc_talisman_energy_i01"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
</list>

=== Gurtovoy/antharasl2/gameserver/data/items/13700-13799.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="13752" name="Olympiad Warrior\'s Ring">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="A"/>
		<set name="icon" value="icon.accessory_ring_of_hero_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="150"/>
		<equip>
			<slot id="RIGHT_FINGER"/>
			<slot id="LEFT_FINGER"/>
		</equip>
		<for>
			<add stat="mDef" order="0x10" value="42"/>
			<add stat="maxMp" order="0x60" value="21"/>
		</for>
	</armor>
	<armor id="13753" name="Olympiad Warrior\'s Necklace">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="A"/>
		<set name="icon" value="icon.accessory_necklace_of_hero_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="150"/>
		<equip>
			<slot id="NECKLACE"/>
		</equip>
		<for>
			<add stat="mDef" order="0x10" value="85"/>
			<add stat="maxMp" order="0x60" value="42"/>
		</for>
	</armor>
	<armor id="13754" name="Olympiad Warrior\'s Earring">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="A"/>
		<set name="icon" value="icon.accessory_earring_of_hero_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="150"/>
		<equip>
			<slot id="RIGHT_EAR"/>
			<slot id="LEFT_EAR"/>
		</equip>
		<for>
			<add stat="mDef" order="0x10" value="63"/>
			<add stat="maxMp" order="0x60" value="31"/>
		</for>
	</armor>
</list>

=== Gurtovoy/antharasl2/gameserver/data/items/20600-20699.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="20662" name="Agathion - Uthanka">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="freightable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="BranchSys.icon.br_aga_uthanka_i00"/>
		<set name="tradeable" value="false"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="150"/>
		<equip>
			<slot id="LEFT_BRACELET"/>
		</equip>
		<skills>
			<skill id="3267" level="1"/>
			<skill id="21109" level="1"/>
			<skill id="23087" level="1"/>
		</skills>
	</armor>
	<armor id="20666" name="Valkyrie Hat">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="BranchSys.icon.br_valkyrie_cap_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
	<armor id="20678" name="Gatekeeper Hat">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="BranchSys.icon.br_gatekeeper_of_hat_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
</list>

=== Gurtovoy/antharasl2/gameserver/data/items/13500-13599.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="13501" name="Refined Romantic Chapeau">
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.accessory_archer_hat2_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
	<armor id="13519" name="Gran Kain\'s Black Mask &lt;Str+1 Int+1&gt;">
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.accessory_jjoro_masj_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
		<skills>
			<skill id="39062" level="1"/>
		</skills>
		<for>	<!--TODO: Вынести в скиллы!-->
			<add stat="STR" order="0x10" value="1"/>
			<add stat="INT" order="0x10" value="1"/>
		</for>
	</armor>
	<armor id="13520" name="Event - Jindo Dog Hat">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.accessory_jindo_cap_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
	<armor id="13521" name="Event - Shaggy Dog Hat">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.accessory_sapsal_cap_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
</list>

=== Gurtovoy/antharasl2/gameserver/data/items/21100-21199.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<armor id="21162" name="Wedding Veil">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="BranchSys2.icon.br_wedding_vail_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="10"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
	<weapon id="21163" name="Wedding Bouquet">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="BranchSys2.icon.br_wedding_bouquet_i00"/>
		<set name="type" value="ETC"/>
		<set name="weight" value="1600"/>
		<set name="soulshots" value="1"/>
		<set name="spiritshots" value="1"/>
		<set name="rnd_dam" value="1"/>
		<equip>
			<slot id="RIGHT_HAND"/>
		</equip>
		<for>
			<add stat="pAtk" order="0x10" value="1"/>
			<add stat="mAtk" order="0x10" value="1"/>
			<set stat="basePAtkSpd" order="0x08" value="379"/>
			<set stat="basePCritRate" order="0x08" value="10"/>
		</for>
	</weapon>
	<armor id="21165" name="Agathion - Zaken\'s Spirit Swords">
		<set name="is_olympiad_can_use" value="false"/>
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="BranchSys2.Icon.br_aga_zaken_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="150"/>
		<equip>
			<slot id="LEFT_BRACELET"/>
		</equip>
		<skills>
			<skill id="55417" level="1"/>
			<skill id="55441" level="1"/>
			<skill id="3267" level="1"/>
		</skills>
	</armor>
</list>

=== Gurtovoy/antharasl2/gameserver/data/items/91000-91099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<etcitem id="91000" name="Rush\'s Supplies - Baium">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="icon.bm_pirate_treasure_box"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="handler" value="SkillsReduce"/>
		<skills>
			<skill id="51067" level="1"/>	<!--Rush's Supplies - Баюм-->
		</skills>
	</etcitem>
	<etcitem id="91001" name="Box with 3 Jewels Lv. 3">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="icon.etc_bm_jewelbox_shhadai"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91002" name="Box with 5 Jewels Lv. 4">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="icon.etc_bm_jewelbox_shhadai"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<armor id="91003" name="Agathion Bracelet - Lv. 1" add_name="1-day">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.agathion_magmeld_teleport"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="100"/>
		<equip>
			<slot id="LEFT_BRACELET"/>
		</equip>
		<skills>
			<skill id="51025" level="1"/>	<!--Expand Primary and Secondary Agathion Slots-->
		</skills>
	</armor>
	<armor id="91004" name="Agathion - Sin Eater">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="destroyable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.etc_leash_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="50"/>
		<equip>
			<slot id="AGATHION"/>
		</equip>
		<agathion_data>
			<enchant level="0">
				<main_skills>
					<skill id="51068" level="1"/><!--Summon Sin Eater Agathion-->
				</main_skills>
			</enchant>
		</agathion_data>
	</armor>
	<etcitem id="91005" name="Crumbs of Penitence">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="icon.etc_powder_white_i00"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="type" value="QUEST"/>
	</etcitem>
	<armor id="91006" name="Damaged Zaken\'s Earring">
		<set name="sellable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.accessory_earring_of_zaken_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="150"/>
		<equip>
			<slot id="RIGHT_EAR"/>
			<slot id="LEFT_EAR"/>
		</equip>
		<for>
			<add stat="mDef" order="0x10" value="50"/>
		</for>
	</armor>
	<etcitem id="91007" name="Rush\'s Supplies - Zaken">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="icon" value="icon.bm_pirate_treasure_box"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="handler" value="SkillsReduce"/>
		<skills>
			<skill id="51078" level="1"/>	<!--Rush's Supplies - Zaken -->
		</skills>
	</etcitem>
	<etcitem id="91008" name="Dragon\'s Relic Chest">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.card_event_blue_box"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91009" name="Fire Dragon\'s Relic Chest">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.card_event_red_box"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91010" name="Land Dragon\'s Relic Chest">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.card_event_black_box"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91011" name="Dragon\'s Dye Box" add_name="3rd Class Transfer">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.card_event_gold_box"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91012" name="Weapon Supply Box (Best A-grade)">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i00"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91013" name="Weapon Ingredient/Recipe Box (Top A-grade)">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i00"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91014" name="Weapon Recipe Box (Best A-grade)">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i00"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91015" name="Sirra\'s Blade Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91016" name="Sword of Ipos Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91017" name="Barakiel\'s Axe Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91018" name="Behemoth\' Tuning Fork Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91019" name="Naga Storm Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91020" name="Tiphon\'s Spear Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91021" name="Shyeed\'s Bow Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91022" name="Sobekk\'s Hurricane Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91023" name="Themis\' Tongue Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91024" name="Cabrio\'s Hand Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91025" name="Daimon Crystal Ingredient/Recipe Box">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_treasure_box_i04"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91026" name="Dragon\'s Heart">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.etc_heart_gragon"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91027" name="Dragon\'s Miracle Potion">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="icon.bm_dragon_posion_brave"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="91028" name="Dragon\'s Recovery Potion" add_name="Not Available">
		<set name="sellable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="icon" value="BranchSys.icon.br_vitality_potion_i01"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
</list>

=== Gurtovoy/antharasl2/gameserver/data/items/37700-37799.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">
<list>
	<weapon id="37700" name="Valentine Dual Dagger ">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.ev_hallowinday_candy_i00"/>
		<set name="type" value="DUALDAGGER"/>
		<set name="weight" value="500"/>
		<set name="soulshots" value="1"/>
		<set name="spiritshots" value="1"/>
		<set name="rnd_dam" value="10"/>
		<equip>
			<slot id="LEFT_RIGHT_HAND"/>
		</equip>
		<for>
			<add stat="pAtk" order="0x10" value="752"/>
			<add stat="mAtk" order="0x10" value="414"/>
			<set stat="basePAtkSpd" order="0x08" value="433"/>
			<set stat="basePCritRate" order="0x08" value="120"/>
			<add stat="pAccCombat" order="0x10" value="-3.75"/>
		</for>
	</weapon>
	<weapon id="37701" name="Valentine Dual Blunt Weapon ">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.ev_hallowinday_candy_i00"/>
		<set name="type" value="DUALBLUNT"/>
		<set name="weight" value="500"/>
		<set name="soulshots" value="1"/>
		<set name="spiritshots" value="1"/>
		<set name="rnd_dam" value="20"/>
		<equip>
			<slot id="LEFT_RIGHT_HAND"/>
		</equip>
		<for>
			<add stat="pAtk" order="0x10" value="916"/>
			<add stat="mAtk" order="0x10" value="414"/>
			<set stat="basePAtkSpd" order="0x08" value="325"/>
			<set stat="basePCritRate" order="0x08" value="60"/>
			<add stat="pAccCombat" order="0x10" value="8"/>
		</for>
	</weapon>
	<weapon id="37702" name="Valentine Shield">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.ev_hallowinday_candy_i00"/>
		<set name="type" value="NONE"/>
		<set name="weight" value="1130"/>
		<equip>
			<slot id="LEFT_HAND"/>
		</equip>
		<for>
			<add stat="pEvasRate" order="0x10" value="-8"/>
			<add stat="sDef" order="0x10" value="546"/>
			<add stat="rShld" order="0x10" value="20"/>
		</for>
	</weapon>
	<armor id="37703" name="Valentine Sigil ">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.ev_hallowinday_candy_i00"/>
		<set name="type" value="SIGIL"/>
		<set name="weight" value="920"/>
		<equip>
			<slot id="LEFT_HAND"/>
		</equip>
		<for>
			<add stat="pDef" order="0x10" value="150"/>
		</for>
	</armor>
	<etcitem id="37704" name="Love Potion">
		<set name="icon" value="icon.etc_whiteday_herb"/>
		<set name="crystal_type" value="NONE"/>
	</etcitem>
	<etcitem id="37705" name="Gold Fishing Shot">
		<set name="price" value="56"/>
		<set name="sellable" value="false"/>
		<set name="icon" value="icon.etc_spirit_bullet_fish_i05"/>
		<set name="weight" value="3"/>
		<set name="stackable" value="true"/>
		<set name="crystal_type" value="NONE"/>
		<set name="type" value="FISHSHOT"/>
		<skills>
			<skill id="55326" level="1"/>	<!--Gold Fishing Shot-->
		</skills>
	</etcitem>
	<armor id="37725" name="NC Dinos Uniform">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.london_olympic_bikini"/>
		<set name="type" value="HEAVY"/>
		<set name="weight" value="1000"/>
		<equip>
			<slot id="FORMAL_WEAR"/>
		</equip>
	</armor>
	<armor id="37726" name="NC Dinos Shortstop Cap">
		<set name="sellable" value="false"/>
		<set name="privatestoreable" value="false"/>
		<set name="destroyable" value="false"/>
		<set name="dropable" value="false"/>
		<set name="tradeable" value="false"/>
		<set name="crystal_type" value="NONE"/>
		<set name="icon" value="icon.accessory_mining_cap_i00"/>
		<set name="type" value="NONE"/>
		<equip>
			<slot id="HAIR_ALL"/>
		</equip>
	</armor>
</list>
