=== Gurtovoy/antharasl2/gameserver/data/skills/skill.dtd
<!ELEMENT list (skill)*>

	<!ELEMENT skill  (set|table|for|cond|triggers|enchant|restoration)*>
	<!ATTLIST skill
		id CDATA #REQUIRED
		levels CDATA #REQUIRED
		name CDATA #REQUIRED>

		<!ELEMENT set (player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST set
			name CDATA #IMPLIED
			order CDATA #IMPLIED
			stat CDATA #IMPLIED
			value CDATA #REQUIRED>

		<!ELEMENT table (#PCDATA)>
		<!ATTLIST table
			name CDATA #REQUIRED>

		<!ELEMENT start_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST start_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT tick_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST tick_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

		<!ELEMENT self_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST self_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT pvp_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST pvp_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT pve_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST pve_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			interval CDATA #IMPLIED
			instant CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED
			type CDATA #IMPLIED>

		<!ELEMENT end_effect (def|add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|cond|triggers|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST end_effect
			enabled CDATA #IMPLIED
			name CDATA #IMPLIED
			value CDATA #IMPLIED
			chance CDATA #IMPLIED>

			<!ELEMENT def (#PCDATA)>
			<!ATTLIST def
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT for (add|stat_effect|p_critical_damage|p_magic_critical_dmg|p_skill_critical_damage|p_heal_effect|p_attack_trait|p_defence_trait|p_vampiric_attack|p_mp_vampiric_attack|set|mul|div|sub|start_effect|tick_effect|self_effect|effect|pvp_effect|pve_effect|end_effect)*>

			<!ELEMENT add (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST add
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT stat_effect (set)*>
			<!ATTLIST stat_effect
				name CDATA #REQUIRED
				value CDATA #IMPLIED
				type CDATA #IMPLIED>

			<!ELEMENT p_critical_damage (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_critical_damage
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_magic_critical_dmg (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_magic_critical_dmg
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_skill_critical_damage (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_skill_critical_damage
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_heal_effect (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_heal_effect
				value CDATA #REQUIRED
				type CDATA #REQUIRED>

			<!ELEMENT p_attack_trait (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_attack_trait
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT p_defence_trait (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_defence_trait
				name CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT p_vampiric_attack (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_vampiric_attack
				value CDATA #REQUIRED
				chance CDATA #IMPLIED>

			<!ELEMENT p_mp_vampiric_attack (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST p_mp_vampiric_attack
				value CDATA #REQUIRED
				chance CDATA #IMPLIED>

			<!ELEMENT mul (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST mul
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT div (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST div
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

			<!ELEMENT sub (player|target|using|zone|has|game|or|not|and)*>
			<!ATTLIST sub
				order CDATA #IMPLIED
				stat CDATA #REQUIRED
				value CDATA #REQUIRED>

		<!ELEMENT cond (player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST cond
			msgId CDATA #IMPLIED
			addName CDATA #IMPLIED>

			<!ELEMENT or (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT not (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT and (player|target|using|zone|has|game|or|not|and)*>

			<!ELEMENT player (#PCDATA)>
			<!ATTLIST player
				residence CDATA #IMPLIED
				olympiad CDATA #IMPLIED
				race CDATA #IMPLIED
				instance_zone CDATA #IMPLIED
				is_clan_leader CDATA #IMPLIED
				is_hero CDATA #IMPLIED
				sex CDATA #IMPLIED
				classId CDATA #IMPLIED
				minLevel CDATA #IMPLIED
				max_level CDATA #IMPLIED
				avail_max_sp CDATA #IMPLIED
				quest_state CDATA #IMPLIED
				min_pledge_rank CDATA #IMPLIED
				class_type CDATA #IMPLIED
				summon_siege_golem CDATA #IMPLIED
				running CDATA #IMPLIED
				percentHP CDATA #IMPLIED
				resting CDATA #IMPLIED
				max_level CDATA #IMPLIED
				maxPK CDATA #IMPLIED
				percentMP CDATA #IMPLIED
				moving CDATA #IMPLIED
				standing CDATA #IMPLIED
				damage CDATA #IMPLIED
				percentCP CDATA #IMPLIED
				direction CDATA #IMPLIED
				riding CDATA #IMPLIED
				flying CDATA #IMPLIED
				castle_type CDATA #IMPLIED
				min_clan_level CDATA #IMPLIED
				has_abnormal_type CDATA #IMPLIED
				has_summon_id CDATA #IMPLIED
				can_transform CDATA #IMPLIED
				can_untransform CDATA #IMPLIED
				agathion CDATA #IMPLIED
				hasBuffId CDATA #IMPLIED
				flyingTransform CDATA #IMPLIED
				isFlagged CDATA #IMPLIED
				can_learn_skill CDATA #IMPLIED
				is_chaotic CDATA #IMPLIED>

			<!ELEMENT target (#PCDATA)>
			<!ATTLIST target
				is_pet_feed CDATA #IMPLIED
				type CDATA #IMPLIED
				race CDATA #IMPLIED
				hasForbiddenSkill CDATA #IMPLIED
				mobId CDATA #IMPLIED
				npc_class CDATA #IMPLIED
				castledoor CDATA #IMPLIED
				direction CDATA #IMPLIED
				percentHP CDATA #IMPLIED
				has_abnormal_type CDATA #IMPLIED
				forbiddenClassIds CDATA #IMPLIED
				min_distance CDATA #IMPLIED
				hasBuffId CDATA #IMPLIED
				playerRace CDATA #IMPLIED>

			<!ELEMENT using (#PCDATA)>
			<!ATTLIST using
				slotitem CDATA #IMPLIED
				kind CDATA #IMPLIED
				armor CDATA #IMPLIED
				weapon CDATA #IMPLIED
				skill CDATA #IMPLIED>

			<!ELEMENT zone (#PCDATA)>
			<!ATTLIST zone
				type CDATA #IMPLIED
				name CDATA #IMPLIED>

			<!ELEMENT game (#PCDATA)>
			<!ATTLIST game
				night CDATA #IMPLIED>

			<!ELEMENT has (#PCDATA)>
			<!ATTLIST has
				skill CDATA #IMPLIED>

		<!ELEMENT triggers (trigger)*>
		<!ELEMENT trigger (cond|player|target|using|zone|has|game|or|not|and)*>
		<!ATTLIST trigger
			id CDATA #IMPLIED
			level CDATA #IMPLIED
			type CDATA #IMPLIED
			chance CDATA #IMPLIED
			cancel_effects_on_remove CDATA #IMPLIED
			increasing CDATA #IMPLIED
			delay CDATA #IMPLIED
			args CDATA #IMPLIED>

		<!ELEMENT enchant (table)*>
		<!ATTLIST enchant
			type CDATA #REQUIRED
			levels CDATA #IMPLIED
			group CDATA #IMPLIED
			name CDATA #IMPLIED>

		<!ELEMENT restoration (group)*>
		<!ATTLIST restoration
			level CDATA #REQUIRED
			consume_item_id CDATA #IMPLIED
			consume_item_count CDATA #IMPLIED
			on_fail_message CDATA #IMPLIED>

			<!ELEMENT group (item)*>
			<!ATTLIST group
				chance CDATA #REQUIRED>

				<!ELEMENT item (#PCDATA)>
				<!ATTLIST item
					id CDATA #REQUIRED
					min_count CDATA #REQUIRED
					max_count CDATA #IMPLIED
					enchant_level CDATA #IMPLIED>

=== Gurtovoy/antharasl2/gameserver/data/skills/23200-23299.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="23234" levels="1" name="Singer &amp; Dancer Agathion Cute Trick">
		<set name="icon" value="icon.skill_agathion_cute"/>
		<set name="hitTime" value="3000"/>
		<set name="ride_state" value="NONE;STRIDER;WYVERN;WOLF"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<set name="isReuseDelayPermanent" value="true"/>
		<cond msgId="2292">
			<player agathion="-1"/>
		</cond>
	</skill>
	<skill id="23298" levels="1" name="Flame Hawk">
		<set name="debuff" value="true"/>
		<set name="icon" value="icon.skill0771"/>
		<set name="abnormal_effect" value="DOT_BLEEDING"/>
		<set name="abnormal_time" value="10"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="dot_attr"/>
		<set name="magicLevel" value="83"/>
		<set name="lv_bonus_rate" value="1"/>
		<set name="target" value="TARGET_ONE"/>
		<set name="skillType" value="DEBUFF"/>
		<set name="operate_type" value="A2"/>
		<for>
			<effect name="t_hp" interval="1" value="-150"/>
		</for>
	</skill>
	<skill id="23299" levels="1" name="Arrow Rain">
		<set name="debuff" value="true"/>
		<set name="effectPoint" value="100"/>
		<set name="icon" value="icon.skill0772"/>
		<set name="abnormal_effect" value="DOT_BLEEDING"/>
		<set name="abnormal_time" value="10"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="dot_attr"/>
		<set name="magicLevel" value="83"/>
		<set name="lv_bonus_rate" value="1"/>
		<set name="target" value="TARGET_ONE"/>
		<set name="skillType" value="DEBUFF"/>
		<set name="operate_type" value="A2"/>
		<for>
			<effect name="t_hp" interval="1" value="-150"/>
		</for>
	</skill>
</list>

=== Gurtovoy/antharasl2/gameserver/data/skills/14000-14099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="14000" levels="1" name="Berserk">
		<set name="effectPoint" value="100"/>
		<set name="icon" value="icon.skill1062"/>
		<set name="reuseDelay" value="6000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="14001" levels="3" name="Cross Slash">
		<table name="#magicLevel">95 96 97</table>
		<table name="#mp_consume">85 86 86</table>
		<set name="effectPoint" value="-354"/>
		<set name="icon" value="icon.skill0003"/>
		<set name="reuseDelay" value="2500"/>
		<set name="castRange" value="150"/>
		<set name="hitTime" value="1500"/>
		<set name="mp_consume" value="#mp_consume"/>
		<set name="magicLevel" value="#magicLevel"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="14002" levels="3" name="Transfixion Attack">
		<table name="#magicLevel">95 96 97</table>
		<table name="#effectPoint">-352 -353 -353</table>
		<set name="effectPoint" value="#effectPoint"/>
		<set name="icon" value="icon.skill0484"/>
		<set name="reuseDelay" value="5000"/>
		<set name="castRange" value="400"/>
		<set name="hitTime" value="100"/>
		<set name="mp_consume" value="20"/>
		<set name="magicLevel" value="#magicLevel"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="14055" levels="2" name="Power Shot">
		<table name="#mp_consume">83 84</table>
		<table name="#effectPoint">-150 -200</table>
		<set name="effectPoint" value="#effectPoint"/>
		<set name="icon" value="icon.skill0056"/>
		<set name="reuseDelay" value="5000"/>
		<set name="castRange" value="700"/>
		<set name="hitTime" value="3000"/>
		<set name="mp_consume" value="#mp_consume"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
</list>

=== Gurtovoy/antharasl2/gameserver/data/skills/10000-10099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="10015" levels="2" name="Chain Strike">
		<table name="#magicLevel">76 82</table>
		<table name="#activateRate">60 75</table>
		<table name="#mp_consume">69 73</table>
		<table name="#effectPoint">-2066 -2099</table>
		<set name="debuff" value="true"/>
		<set name="effectPoint" value="#effectPoint"/>
		<set name="icon" value="icon.skill10015"/>
		<set name="reuseDelay" value="15000"/>
		<set name="coolTime" value="1000"/>
		<set name="castRange" value="600"/>
		<set name="hitTime" value="1000"/>
		<set name="mp_consume" value="#mp_consume"/>
		<set name="abnormal_time" value="1"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="stun"/>
		<set name="magicLevel" value="#magicLevel"/>
		<set name="activateRate" value="#activateRate"/>
		<set name="nextAction" value="attack"/>
		<set name="lv_bonus_rate" value="30"/>
		<set name="target" value="TARGET_ONE"/>
		<set name="trait" value="PULL"/>
		<set name="skillType" value="DEBUFF"/>
		<set name="operate_type" value="A2"/>
		<cond msgId="113">
			<using kind="Shield"/>
		</cond>
		<for>
			<effect name="ThrowHorizontal">
				<def name="fly_speed" value="600"/>
				<def name="fly_delay" value="600"/>
			</effect>
		</for>
	</skill>
	<skill id="10094" levels="2" name="Mass Lightning Strike">
		<table name="#mp_consume">140 146</table>
		<table name="#effectPoint">-828 -848</table>
		<set name="debuff" value="true"/>
		<set name="effectPoint" value="#effectPoint"/>
		<set name="icon" value="icon.skll10094"/>
		<set name="reuseDelay" value="60000"/>
		<set name="coolTime" value="500"/>
		<set name="castRange" value="400"/>
		<set name="hitTime" value="1500"/>
		<set name="mp_consume" value="#mp_consume"/>
		<set name="abnormal_effect" value="PARALYZE"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_time" value="5"/>
		<set name="activateRate" value="60"/>
		<set name="magicLevel" value="80"/>
		<set name="operate_type" value="A2"/>
		<set name="power" value="1997"/>
		<set name="skillType" value="PDAM"/>
		<set name="target" value="TARGET_AREA"/>
		<set name="affect_range" value="200"/>
		<set name="trait" value="PARALYZE"/>
		<set name="itemConsumeId" value="1785"/>
		<set name="itemConsumeCount" value="1"/>
		<for>
			<effect name="Paralyze"/>
		</for>
	</skill>
</list>

=== Gurtovoy/antharasl2/gameserver/data/skills/56000-56099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="56000" levels="1" name="Stable Scroll: Enchant Cloak">
		<set name="icon" value="icon.skill0000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56001" levels="1" name="High-grade Life Stone Pack - Legendary">
		<set name="icon" value="icon.skill0000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="500"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56002" levels="1" name="High-grade Life Stone Pack - Cloak">
		<set name="icon" value="icon.skill0000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="500"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56003" levels="1" name="XP &amp; SP Rune - 50%">
		<set name="icon" value="icon.skill19226"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56004" levels="1" name="Summon Agathion - Mermaid">
		<set name="icon" value="icon.etc_summon_aga_agit_i00"/>
		<set name="hitTime" value="3000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56005" levels="1" name="Agathion Mermaid Enchant Scroll">
		<set name="icon" value="icon.star_scrl_of_ench_ag"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56006" levels="1" name="Master\'s Fishing Potion">
		<set name="icon" value="BranchIcon.etc_sign_agathion_feed_blue_i00"/>
		<set name="reuseDelay" value="60000"/>
		<set name="coolTime" value="500"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56007" levels="1" name="Shining Fishing Box">
		<set name="icon" value="icon.skill0000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="500"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56008" levels="1" name="Fishing XP Scroll">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="5000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56009" levels="11" name="Mermaid Agathion Unique Ability">
		<set name="icon" value="icon.agathion_base"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56010" levels="4" name="Mermaid\'s Blessing">
		<set name="effectPoint" value="379"/>
		<set name="icon" value="icon.skill_agathion_special"/>
		<set name="reuseDelay" value="3600000"/>
		<set name="hitTime" value="1000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56011" levels="1" name="Complete Arms Supplies Pack">
		<set name="icon" value="icon.skill0000"/>
		<set name="coolTime" value="500"/>
		<set name="hitTime" value="500"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56019" levels="1" name="+7 Elmoreden Cloak Box">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="3000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56020" levels="1" name="+7 Aden Cloak Box">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="3000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56021" levels="1" name="+7 Elmore Cloak Box">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="3000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="56022" levels="1" name="+7 Ferios Cloak Box">
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="3000"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
</list>

=== Gurtovoy/antharasl2/gameserver/data/skills/20000-20099.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="20001" levels="1" name="Block Checker Hammer Punch">
		<set name="effectPoint" value="-1"/>
		<set name="icon" value="BranchSys2.icon.br_s_hammerpunch_treasure1_i001"/>
		<set name="reuseDelay" value="60000"/>
		<set name="castRange" value="40"/>
		<set name="hitTime" value="1000"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="20002" levels="1" name="Dragon Kick">
		<set name="effectPoint" value="-347"/>
		<set name="icon" value="icon.skill_transform_s_attack"/>
		<set name="reuseDelay" value="7000"/>
		<set name="coolTime" value="167"/>
		<set name="castRange" value="20"/>
		<set name="hitTime" value="2000"/>
		<set name="mp_consume" value="55"/>
		<set name="magicLevel" value="85"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="20003" levels="1" name="Dragon Slash">
		<set name="effectPoint" value="-348"/>
		<set name="icon" value="icon.skill_transform_s_attack"/>
		<set name="reuseDelay" value="7000"/>
		<set name="coolTime" value="167"/>
		<set name="castRange" value="20"/>
		<set name="hitTime" value="2000"/>
		<set name="mp_consume" value="55"/>
		<set name="magicLevel" value="85"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="20004" levels="1" name="Dragon Dash">
		<set name="effectPoint" value="689"/>
		<set name="icon" value="icon.skill_transform_buff"/>
		<set name="reuseDelay" value="25000"/>
		<set name="mp_consume" value="38"/>
		<set name="abnormal_time" value="5"/>
		<set name="abnormal_level" value="2"/>
		<set name="abnormal_type" value="speed_up_special"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="MAGIC"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
	</skill>
	<skill id="20005" levels="1" name="Dragon Aura">
		<set name="effectPoint" value="635"/>
		<set name="icon" value="icon.skill_transform_buff"/>
		<set name="reuseDelay" value="1800000"/>
		<set name="castRange" value="400"/>
		<set name="hitTime" value="4000"/>
		<set name="mp_consume" value="47"/>
		<set name="abnormal_time" value="1200"/>
		<set name="abnormal_level" value="3"/>
		<set name="abnormal_type" value="improve_crt_rate_dmg_up"/>
		<set name="magicLevel" value="70"/>
		<set name="magicType" value="MAGIC"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTDONE"/>
		<set name="operate_type" value="A2"/>
		<for>
			<effect name="p_block_buff_slot">
				<def name="abnormal_types" value="critical_prob_up;critical_dmg_up"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="critical_prob_up"/>
				<def name="max_abnormal_level" value="9"/>
			</effect>
			<effect name="i_dispel_by_slot">
				<def name="abnormal_type" value="critical_dmg_up"/>
				<def name="max_abnormal_level" value="9"/>
			</effect>
		</for>
	</skill>
	<skill id="20006" levels="1" name="Soul Roar">
		<set name="effectPoint" value="635"/>
		<set name="icon" value="BranchSys2.icon.skill20006"/>
		<set name="reuseDelay" value="240000"/>
		<set name="hitTime" value="1500"/>
		<set name="mp_consume" value="58"/>
		<set name="abnormal_time" value="600"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="max_hp_up_k"/>
		<set name="magicLevel" value="62"/>
		<set name="hitCancelTime" value="350"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<for>
			<effect>
				<mul stat="maxHp" value="1.15"/>
				<mul stat="maxCp" value="1.15"/>
			</effect>
			<effect instant="true" name="RestoreHP" value="15">
				<def name="percent" value="true"/>
			</effect>
			<effect instant="true" name="RestoreCP" value="15">
				<def name="percent" value="true"/>
			</effect>
		</for>
	</skill>
</list>

=== Gurtovoy/antharasl2/gameserver/data/skills/14700-14799.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="14765" levels="5" name="Blood Siphon Resistance">
		<set name="icon" value="icon.skillraid"/>
		<set name="target" value="TARGET_NONE"/>
		<set name="skillType" value="NOTUSED"/>
		<set name="operate_type" value="P"/>
	</skill>
	<skill id="14767" levels="1" name="Siege Punch">
		<set name="effectPoint" value="-100"/>
		<set name="icon" value="icon.skill0000"/>
		<set name="reuseDelay" value="5000"/>
		<set name="hitTime" value="4600"/>
		<set name="magicLevel" value="85"/>
		<set name="affect_range" value="600"/>
		<set name="target" value="TARGET_AURA"/>
		<set name="skillType" value="PDAM"/>
		<set name="operate_type" value="A2"/>
		<set name="power" value="31500"/>
	</skill>
</list>

=== Gurtovoy/antharasl2/gameserver/data/skills/21100-21199.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="21109" levels="1" name="Summon Agathion - Uthanka">
		<set name="icon" value="icon.etc_summon_aga_agit_i00"/>
		<set name="hitTime" value="3000"/>
		<set name="ride_state" value="NONE;STRIDER;WYVERN;WOLF"/>
		<set name="magicLevel" value="85"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<set name="isReuseDelayPermanent" value="true"/>
		<set name="useSS" value="false"/>
		<for>
			<effect name="i_summon_agathion" value="533"/>
		</for>
	</skill>
</list>

=== Gurtovoy/antharasl2/gameserver/data/skills/9400-9499.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "skill.dtd">
<list>
	<skill id="9487" levels="1" name="Angel Cat\'s Blessing">
		<set name="effectPoint" value="1"/>
		<set name="icon" value="icon.skilltransform4"/>
		<set name="olympiad_use" value="false"/>
		<set name="ride_state" value="NONE;STRIDER;WYVERN;WOLF"/>
		<set name="abnormal_time" value="3600"/>
		<set name="abnormal_level" value="1"/>
		<set name="abnormal_type" value="br_event_buf3"/>
		<set name="magicLevel" value="1"/>
		<set name="magicType" value="SPECIAL"/>
		<set name="isHandler" value="true"/>
		<set name="target" value="TARGET_SELF"/>
		<set name="skillType" value="BUFF"/>
		<set name="operate_type" value="A2"/>
		<set name="isSelfDispellable" value="false"/>
		<set name="isPreservedOnDeath" value="true"/>
		<for>
			<effect>
				<mul stat="maxHp" value="1.05"/>
				<mul stat="maxMp" value="1.05"/>
				<add stat="exp_rate_multiplier" value="0.2"/>
				<add stat="sp_rate_multiplier" value="0.2"/>
			</effect>
		</for>
	</skill>
</list>
